"""System-generated prototype certificate PDF (ReportLab). NOT legally/digitally signed."""
import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

ART_DIR = os.path.join(os.path.dirname(__file__), "artifacts")
os.makedirs(ART_DIR, exist_ok=True)


def generate_certificate_pdf(cert: dict) -> str:
    path = os.path.join(ART_DIR, f"{cert['id']}.pdf")
    c = canvas.Canvas(path, pagesize=A4)
    w, h = A4
    c.setFillColorRGB(0.078, 0.078, 0.078)
    c.rect(0, h - 45 * mm, w, 45 * mm, fill=1, stroke=0)
    c.setFillColorRGB(0.96, 0.83, 0.29)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(20 * mm, h - 25 * mm, "SOA · Institutional Service Platform")
    c.setFillColorRGB(1, 1, 1)
    c.setFont("Helvetica", 12)
    c.drawString(20 * mm, h - 35 * mm, cert.get("certificateType", "Bonafide Certificate"))

    c.setFillColorRGB(0.078, 0.078, 0.078)
    y = h - 70 * mm
    rows = [
        ("Certificate ID", cert["id"]),
        ("Verification / Reference ID", cert.get("verificationId", "")),
        ("Linked Request ID", cert.get("requestId", "")),
        ("Student / Requester", cert.get("requester", "")),
        ("SOA ID", cert.get("soaId", "—")),
        ("Purpose", cert.get("purpose", "")),
        ("Approving Authority", cert.get("approver", "")),
        ("Approval Timestamp", cert.get("approvedAt", "")),
        ("Issue Date", cert.get("issueDate", "")),
    ]
    for label, val in rows:
        c.setFont("Helvetica-Bold", 11)
        c.drawString(20 * mm, y, f"{label}:")
        c.setFont("Helvetica", 11)
        c.drawString(85 * mm, y, str(val))
        y -= 10 * mm

    c.setFillColorRGB(0.5, 0.4, 0.05)
    c.setFont("Helvetica-Oblique", 9)
    c.drawString(20 * mm, 25 * mm,
                 "System-generated prototype document — not a legally/digitally signed institutional certificate.")
    c.setFillColorRGB(0.55, 0.55, 0.55)
    c.drawString(20 * mm, 18 * mm, f"Generated by SOA governed workflow · {cert.get('issueDate','')}")
    c.showPage()
    c.save()
    return path
